let cube = [
    "Crush of Tentacles",
    "Fall of the Titans",
    "Overwhelming Denial",
    "Tyrant of Valakut",
    "Nimbus Champion",
    "Rushblade Commander",
    "Thrasher Brute",
    "Booster Tutor",
    "Buzzing Whack-a-Doodle",
    "Crow Storm",
    "Etali, Primal Storm",
    "Hunting Pack",
    "Entirely Normal Armchair",
    "Everythingamajig",
    "Giant Fan",
    "Modular Monstrosity",
    "Pointy Finger of Doom",
    "Split Screen",
    "Sword of Dungeons & Dragons",
    "Urza, Academy Headmaster",
    "X",
    "Archfiend of Despair",
    "Archon of Valor's Reach",
    "Beast Within",
    "Blood Feud",
    "Boldwyr Intimidator",
    "Bonus Round",
    "Bramble Sovereign",
    "Bring Down",
    "Chain Lightning",
    "Hot Soup",
    "Key to the City",
    "Open into Wonder",
    "Whirler Rogue",
    "Wings of Hubris",
    "Altar of Dementia",
    "Feral Hydra",
    "Fog Bank",
    "Fumble",
    "Game Plan",
    "Gang Up",
    "Generous Patron",
    "Genesis Chamber",
    "Tezzeret's Gambit",
    "Grothama, All-Devouring",
    "Hunted Wumpus",
    "Lava-Field Overlord",
    "Magus of the Candelabra",
    "Mystic Confluence",
    "Noosegraf Mob",
    "Oracle's Insight",
    "Pir's Whim",
    "Play of the Game",
    "Regna's Sanction",
    "Sentinel Tower",
    "Stolen Strategy",
    "Stunning Reversal",
    "Take Up Arms",
    "The Crowd Goes Wild",
    "Thrilling Encore",
    "Together Forever",
    "Vampire Charmseeker",
    "Spectral Searchlight",
    "Virtus's Maneuver",
    "Zndrsplt's Judgment",
    "Gladehart Cavalry",
    "Immolating Glare",
    "Archmage's Charm",
    "Birthing Boughs",
    "Generous Gift",
    "Watcher for Tomorrow",
    "Wing Shards",
    "Acidic Slime",
    "Unicycle",
    "Bag of Holding",
    "Mardu Shadowspear",
    "Davriel, Rogue Shadowmage",
    "Jace Beleren",
    "Managorger Hydra",
    "Rishkar, Peema Renegade",
    "Jiang Yanggu, Wildcrafter",
    "Akroan Horse",
    "Fractured Identity",
    "Sepulchral Primordial",
    "Mistmeadow Witch",
    "Samut, Tyrant Smasher",
    "Tattermunge Witch",
    "Apocalypse Hydra",
    "Joraga Auxiliary",
    "Huatli's Raptor",
    "Bloodfell Caves",
    "Blossoming Sands",
    "Rugged Highlands",
    "Tranquil Cove",
    "Dismal Backwater",
    "Temple of Enlightenment",
    "Temple of Deceit",
    "Sulfurous Springs",
    "Temple of Plenty",
    "Bountiful Promenade",
    "Luxury Suite",
    "Morphic Pool",
    "Sea of Clouds",
    "Spire Garden",
    "Geier Reach Sanitarium",
    "Gutterbones",
    "Narnam Renegade",
    "Zurgo Bellstriker",
    "Decorated Champion",
    "Glory-Bound Initiate",
    "Goblin Cratermaker",
    "Mindblade Render",
    "Reassembling Skeleton",
    "Mardu Strike Leader",
    "Najeela, the Blade-Blossom",
    "Frontier Warmonger",
    "Flamerush Rider",
    "Secure the Wastes",
    "Faerie Guidemother",
    "Aurora Champion",
    "Sandsteppe Outcast",
    "Long Road Home",
    "Trapped in the Tower",
    "Light of Hope",
    "Spellweaver Duo",
    "Negate",
    "Containment Membrane",
    "Huddle Up",
    "Soaring Show-Off",
    "Disowned Ancestor",
    "Fan Favorite",
    "Bloodborn Scoundrels",
    "Mind Rake",
    "Painful Lesson",
    "Bloodlust Inciter",
    "Azra Bladeseeker",
    "Stadium Vendors",
    "Goblin Freerunner",
    "Magma Hellion",
    "Firebolt",
    "Boulder Salvo",
    "Reckless Charge",
    "Jungle Delver",
    "Jungle Wayfinder",
    "Fertilid",
    "Orchard Elemental",
    "Elvish Fury",
    "Combo Attack",
    "Charging Binox",
    "Liliana's Specter",
    "Grave Scrabbler",
    "Mardu Skullhunter",
    "Lieutenants of the Guard",
    "Release to the Wind",
    "Pondering Mage",
    "Arcane Denial",
    "Call to Heel",
    "Scrounging Bandar",
    "Selvala's Enforcer",
    "Selvala, Explorer Returned",
    "Banshee of the Dread Choir",
    "Blade of Selves",
    "Caller of the Pack",
    "Warchief Giant",
    "Eager Construct",
    "Tyrant's Machine",
    "Victory Chimes",
    "Night Market Guard",
    "Skittering Surveyor",
    "Spear Spewer",
    "Relief Captain",
    "Charming Prince",
    "Dragonlair Spider",
    "Cloudblazer",
    "Angel of Condemnation",
    "Ajani, Adversary of Tyrants",
    "Mardu Woe-Reaper",
    "Dragon Hunter",
    "Meadowboon",
    "Otherworldly Journey",
    "Galepowder Mage",
    "Sightless Brawler",
    "Condescend",
    "Deep Analysis",
    "Hangman",
    "Avenging Huntbonder",
    "Orzhov Enforcer",
    "Delirium Skeins",
    "Dreadhorde Butcher",
    "Discovery // Dispersal",
    "Regal Bloodlord",
    "Karlov of the Ghost Council",
    "Thundering Djinn",
    "Fevered Visions",
    "Merfolk Skydiver",
    "Lorescale Coatl",
    "Experiment Kraj",
    "Honored Crop-Captain",
    "Skyknight Vanguard",
    "Firemane Avenger",
    "Deathreap Ritual",
    "Forgotten Ancient",
    "Eye of Doom",
    "Ghirapur Orrery",
    "Howling Golem",
    "Runed Servitor",
    "Rousing of Souls",
    "Tragic Arrogance",
    "Dakra Mystic",
    "Dictate of Kruphix",
    "Folio of Fancies",
    "Messenger Jays",
    "Minds Aglow",
    "Psychic Corrosion",
    "Vision Skeins",
    "Innocent Blood",
    "Barter in Blood",
    "Capital Punishment",
    "Triskaidekaphobia",
    "Rankle, Master of Pranks",
    "Burning Inquiry",
    "Dragon Mage",
    "Incendiary Command",
    "Magus of the Wheel",
    "Borderland Explorer",
    "Magus of the Vineyard",
    "Rites of Flourishing",
    "Selvala's Charge",
    "Selvala's Stampede",
    "Passwall Adept",
    "Flux Channeler",
    "Reckless Scholar",
    "Oneirophage",
    "Saltwater Stalwart",
    "Broodbirth Viper",
    "Jwar Isle Avenger",
    "Cairn Wanderer",
    "Cheering Fanatic",
    "Rimrock Knight",
    "Taurean Mauler",
    "Goblin Razerunners",
    "Hero of Oxid Ridge",
    "Three-Headed Goblin",
    "Goblin Wardriver",
    "Thrill of Possibility",
    "Strategy, Schmategy",
    "Khorvath's Fury",
    "Chainweb Aracnir",
    "Evolution Sage",
    "Maulfist Revolutionary",
    "Signal Pest",
    "Flameblade Adept",
    "Goblin Motivator",
    "Grim Initiate",
    "Seeker of the Way",
    "Accorder Paladin",
    "Daring Skyjek",
    "Lone Rider",
    "Diamond Knight",
    "Raging Redcap",
    "Hero of Bladehold",
    "Avaricious Dragon",
    "Backdraft Hellkite",
    "Mirrorwing Dragon",
    "Hellkite Charger",
    "Steel Hellkite",
    "Basilisk Collar",
    "Fountain of Renewal",
    "Gingerbrute",
    "Haazda Marshal",
    "Hopeful Eidolon",
    "Shadowspear",
    "Swords to Plowshares",
    "Ajani's Pridemate",
    "Vizkopa Guildmage",
    "Angel of Vitality",
    "Consuming Vapors",
    "Bond of Discipline",
    "Ob Nixilis of the Black Oath",
    "Blade of the Bloodchief",
    "Deathgreeter",
    "Hunger of the Howlpack",
    "Tragic Slip",
    "Veteran Explorer",
    "Epochrasite",
    "Shadows of the Past",
    "Fecundity",
    "Filigree Familiar",
    "Falkenrath Noble",
    "Poison-Tip Archer",
    "Screeching Buzzard",
    "Solemn Simulacrum",
    "Vindictive Lich",
    "Mitotic Slime",
    "Harvester of Souls",
    "Reaper from the Abyss",
    "Scuttling Doom Engine",
    "Lore Broker",
    "Mind's Eye",
    "Psychosis Crawler",
    "Chasm Skulker",
    "Niv-Mizzet, the Firemind",
    "Humble Defector",
    "Windfall",
    "Stuffy Doll",
    "Scoured Barrens",
    "Swiftwater Cliffs",
    "Thornwood Falls",
    "Jungle Hollow",
    "Wind-Scarred Crag",
    "Temple of Epiphany",
    "Temple of Malady",
    "Temple of Mystery",
    "Temple of Silence",
    "Roalesk, Apex Hybrid",
    "Outlaws' Merriment",
    "Righteous Confluence",
    "Victory's Herald",
    "Pianna, Nomad Captain",
    "Cultivator of Blades",
    "Rabble-Rouser",
    "Thunderstaff",
    "Trumpet Blast",
    "Rhox Veteran",
    "Battlefield Promotion",
    "Makeshift Battalion",
    "Sunscorch Regent",
    "Do-It-Yourself Seraph",
    "Herald of the Host",
    "Kenrith, the Returned King",
    "Dwarven Lightsmith",
    "Giant Killer",
    "Disenchant",
    "Benthic Biomancer",
    "Faerie Vandal",
    "Nadir Kraken",
    "Vigean Graftmage",
    "Helium Squirter",
    "Jace's Erasure",
    "Ominous Seas",
    "Grip of the Roil",
    "Out of Bounds",
    "Diminishing Returns",
    "Comparative Analysis",
    "Corpse Augur",
    "Herald of the Dreadhorde",
    "Exhume",
    "Quest for the Gravelord",
    "Contentious Plan",
    "Pollenbright Druid",
    "Thrummingbird",
    "Courage in Crisis",
    "Volt Charge",
    "Bloom Hulk",
    "Spread the Sickness",
    "Planewide Celebration",
    "Collective Defiance",
    "Cathartic Reunion",
    "Fire Prophecy",
    "Fists of Flame",
    "Anje's Ravager",
    "Lightning Strike",
    "Cavalier of Thorns",
    "Pulse of Murasa",
    "Regrowth",
    "Caustic Caterpillar",
    "Thrashing Brontodon",
    "Nest Invader",
    "Awakening Zone",
    "Endless One",
    "Mindless Automaton",
    "Weapon Rack",
    "Karn's Bastion",
    "Winding Way",
    "Satyr Wayfinder",
    "Predator's Howl",
    "Status // Statue",
    "Opt",
    "Brainstorm",
    "Alirios, Enraptured",
    "Creepy Doll",
    "Duplicant",
    "Breaker of Armies",
    "Blinkmoth Urn",
    "Coveted Jewel",
    "Howling Mine",
    "Deadeye Navigator",
    "Druid's Familiar",
    "Elgaud Shieldmate",
    "Lightning Mauler",
    "Nearheath Pilgrim",
    "Silverblade Paladin",
    "Tandem Lookout",
    "Wingcrafter",
    "Wolfir Silverheart",
    "Opportunity",
    "Incubation Druid",
    "Merfolk Branchwalker",
    "Voyaging Satyr",
    "Garruk Wildspeaker",
    "Avatar of Growth",
    "Slippery Bogbonder",
    "Wilt",
    "Farfinder",
    "Evolving Wilds",
    "Terramorphic Expanse",
    "Lore Seeker",
    "Cogwork Librarian",
    "Roon of the Hidden Realm",
    "Vaevictis Asmadi, the Dire",
    "Gahiji, Honored One",
    "Tayam, Luminous Enigma",
    "Volrath, the Shapestealer",
    "Mathas, Fiend Seeker",
    "Whirlwind of Thought",
    "Sydri, Galvanic Genius",
    "Kalamax, the Stormsire",
    "City of Brass",
    "Hangarback Walker",
    "Whispering Madness",
    "Stormfist Crusader",
    "Kambal, Consul of Allocation",
    "Chevill, Bane of Monsters",
    "Edric, Spymaster of Trest",
    "The Royal Scions",
    "Expansion // Explosion",
    "Waves of Aggression",
    "Adarkar Wastes",
    "Karplusan Forest",
    "Underground River",
    "Battlefield Forge",
    "Caves of Koilos",
    "Llanowar Wastes",
    "Yavimaya Coast",
    "Shivan Reef",
    "Brushland",
    "Chain of Vapor",
    "Phantom Warrior",
    "Shoulder to Shoulder",
    "Wanderer's Strike",
    "Expedite",
    "Rancor",
    "Syr Konrad, the Grim",
    "Supernatural Stamina",
    "Seer's Lantern",
    "Temple of Malice",
    "Temple of Abandon",
    "Malicious Affliction",
    "Skirsdag High Priest",
    "Lumberknot",
    "Yavimaya Elder",
    "Basri Ket",
    "Angelic Ascension",
    "Heartfire Immolator",
    "Llanowar Visionary",
    "Mazemind Tome",
    "Ghostly Pilferer",
    "Silversmote Ghoul",
    "Liliana, Waker of the Dead",
    "Inspiring Vantage",
    "Twinblade Assassins",
    "Mad Ratter",
    "Irencrag Pyromancer",
    "Gonti, Lord of Luxury",
    "Ardenvale Tactician",
    "Heirloom Blade",
    "Luminate Primordial",
    "Debt to the Deathless",
    "Glint-Horn Buccaneer",
    "God-Pharaoh's Statue",
    "Nicol Bolas, God-Pharaoh",
    "Lightning Reaver",
    "Soul Warden",
    "Sage of Hours",
    "Sarkhan's Unsealing",
    "Skull Rend",
    "The Eldest Reborn",
    "Throne of the God-Pharaoh",
    "Vicious Rumors",
    "Witch of the Moors",
    "Zhur-Taa Druid",
    "Angel of Destiny",
    "Attended Healer",
    "Archpriest of Iona",
    "Journey to Oblivion",
    "Luminarch Aspirant",
    "Squad Commander",
    "Acquisitions Expert",
    "Coveted Prize",
    "Deadly Alliance",
    "Demon's Disciple",
    "Malakir Blood-Priest",
    "Marauding Blight-Priest",
    "Nighthawk Scavenger",
    "Nullpriest of Oblivion",
    "Fireblade Charger",
    "Kargan Intimidator",
    "Roiling Vortex",
    "Shatterskull Charger",
    "Valakut Exploration",
    "Oran-Rief Ooze",
    "Grasp of Fate",
    "Approach of the Second Sun",
    "Deadly Designs",
    "Chain of Smog",
    "Liliana's Caress",
    "Reflector Mage",
    "Vault of Champions",
    "Training Center",
    "Undergrowth Stadium",
    "Spectator Seating",
    "Rejuvenating Springs"
    ]

let partners = [["Proud Mentor", "Impetuous Protege"], ["Sylvia Brightspear", "Khorvath Brightflame"], ["Blaring Recruiter", "Blaring Captain"], ["Regna, the Redeemer", "Krav, the Unredeemed"], ["Lore Weaver", "Ley Weaver"], ["Toothy, Imaginary Friend", "Pir, Imaginative Rascal"], ["Chakram Retriever", "Chakram Slinger"], ["Zndrsplt, Eye of Wisdom", "Okaun, Eye of Chaos"], ["Will Kenrith", "Rowan Kenrith"], ["Nikara, Lair Scavenger", "Yannik, Scavenging Sentinel"], ["Virtus the Veiled", "Gorm the Great"], ["Soulblade Corrupter", "Soulblade Renewer"], ["Brallin, Skyshark Rider", "Shabraz, the Skyshark"], ["Cazur, Ruthless Stalker", "Ukkima, Stalking Shadow"]]


let reset = document.getElementById("reset");
let generate = document.getElementById("generate");
let team1 = document.getElementById("team1");
let team2 = document.getElementById("team2");

let wrap = document.querySelector(".wrap");
let team1Wrap = document.querySelector(".team1");
let team2Wrap = document.querySelector(".team2");







let one = document.getElementById("pack1");
let two = document.getElementById("pack2")
let three = document.getElementById("pack3");
let four = document.getElementById("pack4");
let five = document.getElementById("pack5");
let six = document.getElementById("pack6");
let seven = document.getElementById("pack7")
let eight = document.getElementById("pack8");


let pack1 = []
let pack2 = []
let pack3 = []
let pack4 = []
let pack5 = []
let pack6 = []
let pack7 = []
let pack8 = []
let pack9 = []
let pack10 = []
let pack11 = []
let pack12 = []
let pack13 = []
let pack14 = []
let pack15 = []
let pack16 = []
let pack17 = []
let pack18 = []
let pack19 = []
let pack20 = []
let pack21 = []
let pack22 = []
let pack23 = []
let pack24 = []
let pack25 = []
let pack26 = []
let pack27 = []
let pack28 = []
let pack29 = []
let pack30 = []
let pack31 = []
let pack32 = []
let pack33 = []
let pack34 = []


reset.addEventListener("click", ()=> {
    cube = [
        "Crush of Tentacles",
        "Fall of the Titans",
        "Overwhelming Denial",
        "Tyrant of Valakut",
        "Nimbus Champion",
        "Rushblade Commander",
        "Thrasher Brute",
        "Booster Tutor",
        "Buzzing Whack-a-Doodle",
        "Crow Storm",
        "Etali, Primal Storm",
        "Hunting Pack",
        "Entirely Normal Armchair",
        "Everythingamajig",
        "Giant Fan",
        "Modular Monstrosity",
        "Pointy Finger of Doom",
        "Split Screen",
        "Sword of Dungeons & Dragons",
        "Urza, Academy Headmaster",
        "X",
        "Archfiend of Despair",
        "Archon of Valor's Reach",
        "Beast Within",
        "Blood Feud",
        "Boldwyr Intimidator",
        "Bonus Round",
        "Bramble Sovereign",
        "Bring Down",
        "Chain Lightning",
        "Hot Soup",
        "Key to the City",
        "Open into Wonder",
        "Whirler Rogue",
        "Wings of Hubris",
        "Altar of Dementia",
        "Feral Hydra",
        "Fog Bank",
        "Fumble",
        "Game Plan",
        "Gang Up",
        "Generous Patron",
        "Genesis Chamber",
        "Tezzeret's Gambit",
        "Grothama, All-Devouring",
        "Hunted Wumpus",
        "Lava-Field Overlord",
        "Magus of the Candelabra",
        "Mystic Confluence",
        "Noosegraf Mob",
        "Oracle's Insight",
        "Pir's Whim",
        "Play of the Game",
        "Regna's Sanction",
        "Sentinel Tower",
        "Stolen Strategy",
        "Stunning Reversal",
        "Take Up Arms",
        "The Crowd Goes Wild",
        "Thrilling Encore",
        "Together Forever",
        "Vampire Charmseeker",
        "Spectral Searchlight",
        "Virtus's Maneuver",
        "Zndrsplt's Judgment",
        "Gladehart Cavalry",
        "Immolating Glare",
        "Archmage's Charm",
        "Birthing Boughs",
        "Generous Gift",
        "Watcher for Tomorrow",
        "Wing Shards",
        "Acidic Slime",
        "Unicycle",
        "Bag of Holding",
        "Mardu Shadowspear",
        "Davriel, Rogue Shadowmage",
        "Jace Beleren",
        "Managorger Hydra",
        "Rishkar, Peema Renegade",
        "Jiang Yanggu, Wildcrafter",
        "Akroan Horse",
        "Fractured Identity",
        "Sepulchral Primordial",
        "Mistmeadow Witch",
        "Samut, Tyrant Smasher",
        "Tattermunge Witch",
        "Apocalypse Hydra",
        "Joraga Auxiliary",
        "Huatli's Raptor",
        "Bloodfell Caves",
        "Blossoming Sands",
        "Rugged Highlands",
        "Tranquil Cove",
        "Dismal Backwater",
        "Temple of Enlightenment",
        "Temple of Deceit",
        "Sulfurous Springs",
        "Temple of Plenty",
        "Bountiful Promenade",
        "Luxury Suite",
        "Morphic Pool",
        "Sea of Clouds",
        "Spire Garden",
        "Geier Reach Sanitarium",
        "Gutterbones",
        "Narnam Renegade",
        "Zurgo Bellstriker",
        "Decorated Champion",
        "Glory-Bound Initiate",
        "Goblin Cratermaker",
        "Mindblade Render",
        "Reassembling Skeleton",
        "Mardu Strike Leader",
        "Najeela, the Blade-Blossom",
        "Frontier Warmonger",
        "Flamerush Rider",
        "Secure the Wastes",
        "Faerie Guidemother",
        "Aurora Champion",
        "Sandsteppe Outcast",
        "Long Road Home",
        "Trapped in the Tower",
        "Light of Hope",
        "Spellweaver Duo",
        "Negate",
        "Containment Membrane",
        "Huddle Up",
        "Soaring Show-Off",
        "Disowned Ancestor",
        "Fan Favorite",
        "Bloodborn Scoundrels",
        "Mind Rake",
        "Painful Lesson",
        "Bloodlust Inciter",
        "Azra Bladeseeker",
        "Stadium Vendors",
        "Goblin Freerunner",
        "Magma Hellion",
        "Firebolt",
        "Boulder Salvo",
        "Reckless Charge",
        "Jungle Delver",
        "Jungle Wayfinder",
        "Fertilid",
        "Orchard Elemental",
        "Elvish Fury",
        "Combo Attack",
        "Charging Binox",
        "Liliana's Specter",
        "Grave Scrabbler",
        "Mardu Skullhunter",
        "Lieutenants of the Guard",
        "Release to the Wind",
        "Pondering Mage",
        "Arcane Denial",
        "Call to Heel",
        "Scrounging Bandar",
        "Selvala's Enforcer",
        "Selvala, Explorer Returned",
        "Banshee of the Dread Choir",
        "Blade of Selves",
        "Caller of the Pack",
        "Warchief Giant",
        "Eager Construct",
        "Tyrant's Machine",
        "Victory Chimes",
        "Night Market Guard",
        "Skittering Surveyor",
        "Spear Spewer",
        "Relief Captain",
        "Charming Prince",
        "Dragonlair Spider",
        "Cloudblazer",
        "Angel of Condemnation",
        "Ajani, Adversary of Tyrants",
        "Mardu Woe-Reaper",
        "Dragon Hunter",
        "Meadowboon",
        "Otherworldly Journey",
        "Galepowder Mage",
        "Sightless Brawler",
        "Condescend",
        "Deep Analysis",
        "Hangman",
        "Avenging Huntbonder",
        "Orzhov Enforcer",
        "Delirium Skeins",
        "Dreadhorde Butcher",
        "Discovery // Dispersal",
        "Regal Bloodlord",
        "Karlov of the Ghost Council",
        "Thundering Djinn",
        "Fevered Visions",
        "Merfolk Skydiver",
        "Lorescale Coatl",
        "Experiment Kraj",
        "Honored Crop-Captain",
        "Skyknight Vanguard",
        "Firemane Avenger",
        "Deathreap Ritual",
        "Forgotten Ancient",
        "Eye of Doom",
        "Ghirapur Orrery",
        "Howling Golem",
        "Runed Servitor",
        "Rousing of Souls",
        "Tragic Arrogance",
        "Dakra Mystic",
        "Dictate of Kruphix",
        "Folio of Fancies",
        "Messenger Jays",
        "Minds Aglow",
        "Psychic Corrosion",
        "Vision Skeins",
        "Innocent Blood",
        "Barter in Blood",
        "Capital Punishment",
        "Triskaidekaphobia",
        "Rankle, Master of Pranks",
        "Burning Inquiry",
        "Dragon Mage",
        "Incendiary Command",
        "Magus of the Wheel",
        "Borderland Explorer",
        "Magus of the Vineyard",
        "Rites of Flourishing",
        "Selvala's Charge",
        "Selvala's Stampede",
        "Passwall Adept",
        "Flux Channeler",
        "Reckless Scholar",
        "Oneirophage",
        "Saltwater Stalwart",
        "Broodbirth Viper",
        "Jwar Isle Avenger",
        "Cairn Wanderer",
        "Cheering Fanatic",
        "Rimrock Knight",
        "Taurean Mauler",
        "Goblin Razerunners",
        "Hero of Oxid Ridge",
        "Three-Headed Goblin",
        "Goblin Wardriver",
        "Thrill of Possibility",
        "Strategy, Schmategy",
        "Khorvath's Fury",
        "Chainweb Aracnir",
        "Evolution Sage",
        "Maulfist Revolutionary",
        "Signal Pest",
        "Flameblade Adept",
        "Goblin Motivator",
        "Grim Initiate",
        "Seeker of the Way",
        "Accorder Paladin",
        "Daring Skyjek",
        "Lone Rider",
        "Diamond Knight",
        "Raging Redcap",
        "Hero of Bladehold",
        "Avaricious Dragon",
        "Backdraft Hellkite",
        "Mirrorwing Dragon",
        "Hellkite Charger",
        "Steel Hellkite",
        "Basilisk Collar",
        "Fountain of Renewal",
        "Gingerbrute",
        "Haazda Marshal",
        "Hopeful Eidolon",
        "Shadowspear",
        "Swords to Plowshares",
        "Ajani's Pridemate",
        "Vizkopa Guildmage",
        "Angel of Vitality",
        "Consuming Vapors",
        "Bond of Discipline",
        "Ob Nixilis of the Black Oath",
        "Blade of the Bloodchief",
        "Deathgreeter",
        "Hunger of the Howlpack",
        "Tragic Slip",
        "Veteran Explorer",
        "Epochrasite",
        "Shadows of the Past",
        "Fecundity",
        "Filigree Familiar",
        "Falkenrath Noble",
        "Poison-Tip Archer",
        "Screeching Buzzard",
        "Solemn Simulacrum",
        "Vindictive Lich",
        "Mitotic Slime",
        "Harvester of Souls",
        "Reaper from the Abyss",
        "Scuttling Doom Engine",
        "Lore Broker",
        "Mind's Eye",
        "Psychosis Crawler",
        "Chasm Skulker",
        "Niv-Mizzet, the Firemind",
        "Humble Defector",
        "Windfall",
        "Stuffy Doll",
        "Scoured Barrens",
        "Swiftwater Cliffs",
        "Thornwood Falls",
        "Jungle Hollow",
        "Wind-Scarred Crag",
        "Temple of Epiphany",
        "Temple of Malady",
        "Temple of Mystery",
        "Temple of Silence",
        "Roalesk, Apex Hybrid",
        "Outlaws' Merriment",
        "Righteous Confluence",
        "Victory's Herald",
        "Pianna, Nomad Captain",
        "Cultivator of Blades",
        "Rabble-Rouser",
        "Thunderstaff",
        "Trumpet Blast",
        "Rhox Veteran",
        "Battlefield Promotion",
        "Makeshift Battalion",
        "Sunscorch Regent",
        "Do-It-Yourself Seraph",
        "Herald of the Host",
        "Kenrith, the Returned King",
        "Dwarven Lightsmith",
        "Giant Killer",
        "Disenchant",
        "Benthic Biomancer",
        "Faerie Vandal",
        "Nadir Kraken",
        "Vigean Graftmage",
        "Helium Squirter",
        "Jace's Erasure",
        "Ominous Seas",
        "Grip of the Roil",
        "Out of Bounds",
        "Diminishing Returns",
        "Comparative Analysis",
        "Corpse Augur",
        "Herald of the Dreadhorde",
        "Exhume",
        "Quest for the Gravelord",
        "Contentious Plan",
        "Pollenbright Druid",
        "Thrummingbird",
        "Courage in Crisis",
        "Volt Charge",
        "Bloom Hulk",
        "Spread the Sickness",
        "Planewide Celebration",
        "Collective Defiance",
        "Cathartic Reunion",
        "Fire Prophecy",
        "Fists of Flame",
        "Anje's Ravager",
        "Lightning Strike",
        "Cavalier of Thorns",
        "Pulse of Murasa",
        "Regrowth",
        "Caustic Caterpillar",
        "Thrashing Brontodon",
        "Nest Invader",
        "Awakening Zone",
        "Endless One",
        "Mindless Automaton",
        "Weapon Rack",
        "Karn's Bastion",
        "Winding Way",
        "Satyr Wayfinder",
        "Predator's Howl",
        "Status // Statue",
        "Opt",
        "Brainstorm",
        "Alirios, Enraptured",
        "Creepy Doll",
        "Duplicant",
        "Breaker of Armies",
        "Blinkmoth Urn",
        "Coveted Jewel",
        "Howling Mine",
        "Deadeye Navigator",
        "Druid's Familiar",
        "Elgaud Shieldmate",
        "Lightning Mauler",
        "Nearheath Pilgrim",
        "Silverblade Paladin",
        "Tandem Lookout",
        "Wingcrafter",
        "Wolfir Silverheart",
        "Opportunity",
        "Incubation Druid",
        "Merfolk Branchwalker",
        "Voyaging Satyr",
        "Garruk Wildspeaker",
        "Avatar of Growth",
        "Slippery Bogbonder",
        "Wilt",
        "Farfinder",
        "Evolving Wilds",
        "Terramorphic Expanse",
        "Lore Seeker",
        "Cogwork Librarian",
        "Roon of the Hidden Realm",
        "Vaevictis Asmadi, the Dire",
        "Gahiji, Honored One",
        "Tayam, Luminous Enigma",
        "Volrath, the Shapestealer",
        "Mathas, Fiend Seeker",
        "Whirlwind of Thought",
        "Sydri, Galvanic Genius",
        "Kalamax, the Stormsire",
        "City of Brass",
        "Hangarback Walker",
        "Whispering Madness",
        "Stormfist Crusader",
        "Kambal, Consul of Allocation",
        "Chevill, Bane of Monsters",
        "Edric, Spymaster of Trest",
        "The Royal Scions",
        "Expansion // Explosion",
        "Waves of Aggression",
        "Adarkar Wastes",
        "Karplusan Forest",
        "Underground River",
        "Battlefield Forge",
        "Caves of Koilos",
        "Llanowar Wastes",
        "Yavimaya Coast",
        "Shivan Reef",
        "Brushland",
        "Chain of Vapor",
        "Phantom Warrior",
        "Shoulder to Shoulder",
        "Wanderer's Strike",
        "Expedite",
        "Rancor",
        "Syr Konrad, the Grim",
        "Supernatural Stamina",
        "Seer's Lantern",
        "Temple of Malice",
        "Temple of Abandon",
        "Malicious Affliction",
        "Skirsdag High Priest",
        "Lumberknot",
        "Yavimaya Elder",
        "Basri Ket",
        "Angelic Ascension",
        "Heartfire Immolator",
        "Llanowar Visionary",
        "Mazemind Tome",
        "Ghostly Pilferer",
        "Silversmote Ghoul",
        "Liliana, Waker of the Dead",
        "Inspiring Vantage",
        "Twinblade Assassins",
        "Mad Ratter",
        "Irencrag Pyromancer",
        "Gonti, Lord of Luxury",
        "Ardenvale Tactician",
        "Heirloom Blade",
        "Luminate Primordial",
        "Debt to the Deathless",
        "Glint-Horn Buccaneer",
        "God-Pharaoh's Statue",
        "Nicol Bolas, God-Pharaoh",
        "Lightning Reaver",
        "Soul Warden",
        "Sage of Hours",
        "Sarkhan's Unsealing",
        "Skull Rend",
        "The Eldest Reborn",
        "Throne of the God-Pharaoh",
        "Vicious Rumors",
        "Witch of the Moors",
        "Zhur-Taa Druid",
        "Angel of Destiny",
        "Attended Healer",
        "Archpriest of Iona",
        "Journey to Oblivion",
        "Luminarch Aspirant",
        "Squad Commander",
        "Acquisitions Expert",
        "Coveted Prize",
        "Deadly Alliance",
        "Demon's Disciple",
        "Malakir Blood-Priest",
        "Marauding Blight-Priest",
        "Nighthawk Scavenger",
        "Nullpriest of Oblivion",
        "Fireblade Charger",
        "Kargan Intimidator",
        "Roiling Vortex",
        "Shatterskull Charger",
        "Valakut Exploration",
        "Oran-Rief Ooze",
        "Grasp of Fate",
        "Approach of the Second Sun",
        "Deadly Designs",
        "Chain of Smog",
        "Liliana's Caress",
        "Reflector Mage",
        "Vault of Champions",
        "Training Center",
        "Undergrowth Stadium",
        "Spectator Seating",
        "Rejuvenating Springs"
        ]
   

     partners = [["Proud Mentor", "Impetuous Protege"], ["Sylvia Brightspear", "Khorvath Brightflame"], ["Blaring Recruiter", "Blaring Captain"], ["Regna, the Redeemer", "Krav, the Unredeemed"], ["Lore Weaver", "Ley Weaver"], ["Toothy, Imaginary Friend", "Pir, Imaginative Rascal"], ["Chakram Retriever", "Chakram Slinger"], ["Zndrsplt, Eye of Wisdom", "Okaun, Eye of Chaos"], ["Will Kenrith", "Rowan Kenrith"], ["Nikara, Lair Scavenger", "Yannik, Scavenging Sentinel"], ["Virtus the Veiled", "Gorm the Great"], ["Soulblade Corrupter", "Soulblade Renewer"], ["Brallin, Skyshark Rider", "Shabraz, the Skyshark"], ["Cazur, Ruthless Stalker", "Ukkima, Stalking Shadow"]]
    

    

    // partners = partners.concat(pack1, pack2, pack3, pack4, pack5, pack6, pack7, pack8);
    

    one.innerHTML = ""
    two.innerHTML = ""
    three.innerHTML = ""
    four.innerHTML = ""
    five.innerHTML = ""
    six.innerHTML = ""
    seven.innerHTML = ""
    eight.innerHTML = ""


    // this hides the reset button and reveals the generate button
    generate.classList.remove("hide");
    reset.classList.remove("display");
    team1.classList.toggle("display");
    team2.classList.toggle("display");

    team1Wrap.style.padding = "0"
    wrap.style.maxWidth = "0px"
    wrap.style.padding = "0"
  


})

// this is the event listener for the generate button that runs the shuffleCube function
generate.addEventListener("click", outputPacks);


// Fisher-Yates shuffle function
function shuffle(array) {
    for(let i = array.length - 1; i > 0; i--) {
        let j = Math.floor(Math.random() * (i + 1));
        [array[i], array[j]] = [array[j], array[i]];
    }

    return array
}


// this function takes parameters
function makePacks(pack, arr1, arr2) {

   
    const shuffledCube = shuffle(arr1);
    const shuffledPairs = shuffle(arr2);


     pack = shuffledCube.splice(0, 14);
     
     
     let partners = shuffledPairs.shift([0]);
    
   
     let partner1 = partners[0];
     let partner2 = partners[1];
   
    

     pack.push(partner1);
     pack.push(partner2);



    return pack
}



// this shuffles the cube array and outputs the new random arrays to the webpage
function outputPacks() {

// this hides the generate button and reveals the reset button
  reset.classList.add("display");
  generate.classList.toggle("hide");
  team1.classList.toggle("display");
  team2.classList.toggle("display");

  wrap.style.maxWidth = "900px"
  wrap.style.padding = "1em 2em 1em 2em"

 
  team1Wrap.style.padding = "3em"
  team2Wrap.style.padding = "3em"

  



pack1 = makePacks(pack1, cube, partners);
pack2 = makePacks(pack2, cube, partners);
pack3 = makePacks(pack3, cube, partners);
pack4 = makePacks(pack4, cube, partners);
pack5 = makePacks(pack5, cube, partners);
pack6 = makePacks(pack6, cube, partners);
pack7 = makePacks(pack7, cube, partners);
pack8 = makePacks(pack8, cube, partners);




// output the results to HTML
    one.innerHTML = pack1.join(' <br /> ')
    two.innerHTML = pack2.join(' <br /> ')
    three.innerHTML = pack3.join(' <br /> ')
    four.innerHTML = pack4.join(' <br /> ')
    five.innerHTML = pack5.join(' <br /> ')
    six.innerHTML = pack6.join(' <br /> ')
    seven.innerHTML = pack7.join(' <br /> ')
    eight.innerHTML = pack8.join(' <br /> ')
    // nine.innerHTML = pack9.join(' <br /> ')
    // ten.innerHTML = pack10.join(' <br /> ')
    // eleven.innerHTML = pack11.join(' <br /> ')
    // twelve.innerHTML = pack12.join(' <br /> ')
    // thirteen.innerHTML = pack13.join(' <br /> ')
    // fourteen.innerHTML = pack14.join(' <br /> ')
    // fifteen.innerHTML = pack15.join(' <br /> ')
    // sixteen.innerHTML = pack16.join(' <br /> ')
    // seventeen.innerHTML = pack17.join(' <br /> ')
    // eighteen.innerHTML = pack18.join(' <br /> ')
    // nineteen.innerHTML = pack19.join(' <br /> ')
    // twenty.innerHTML = pack20.join(' <br /> ')
    // twentyOne.innerHTML = pack21.join(' <br /> ')
    // twentyTwo.innerHTML = pack22.join(' <br /> ')
    // twentyThree.innerHTML = pack23.join(' <br /> ')
    // twentyFour.innerHTML = pack24.join(' <br /> ')
    // twentyFive.innerHTML = pack25.join(' <br /> ')
    // twentySix.innerHTML = pack26.join(' <br /> ')
    // twentySeven.innerHTML = pack27.join(' <br /> ')
    // twentyEight.innerHTML = pack28.join(' <br /> ')
    // twentyNine.innerHTML = pack29.join(' <br /> ')
    // thirty.innerHTML = pack30.join(' <br /> ')
    // thirtyOne.innerHTML = pack31.join(' <br /> ')
    // thirtyTwo.innerHTML = pack32.join(' <br /> ')
    // thirtyThree.innerHTML = pack33.join(' <br /> ')
    // thirtyFour.innerHTML = pack34.join(' <br /> ')

   
}

